on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Remove everything except the package
      run: |
        mv packages/uielements.react ../
        ls | grep -v uielements.react | xargs rm -rf
    - name: Push to package branch
      env:
        PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
        VERSION: ${{ github.ref }}
      run: |
        git config --global user.email "marek.magdziak@hotmail.cz"
        git config --global user.name "Marek Magdziak"
        git checkout -b release/$(echo $VERSION | cut -c11-17)
        mv .git ../
        rm -rf ./*
        rm -rf .github
        mv ../.git .git
        cp -r ../uielements.react/* .
        git add -A
        git commit -m "Create package"
        git remote set-url origin https://$PUSH_TOKEN:x-oauth-basic@github.com/mkmarek/unity-react-uielements.git
         git push --set-upstream origin release/$(echo $VERSION | cut -c11-17)
